_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 17
                - 23
                - 55
            "4": 3.11.7
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": darwin-arm64
activation_function:
    value: sigmoid
l_r:
    value: 0.001
neurons_per_layer:
    value:
        - 16
        - 10
        - 5
no_of_epochs:
    value: 400
optimizer:
    value: mini_batch_gradient_descent
