_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 17
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.5
            "8":
                - 1
                - 5
            "12": 0.18.5
            "13": darwin-arm64
dropout_prob:
    value: 0.6
lr:
    value: 0.01
optimizer_type:
    value: sgd
task:
    value: regression
