wandb_version: 1

activation_function:
  value: relu
hidden_layers:
  value: 2
l_r:
  value: 0.001
neurons_per_layer:
  value:
  - 8
no_of_epochs:
  value: 100
optimizer:
  value: mini_batch_gradient_descent
